"""empty message

Revision ID: 099a686e6130
Revises: 
Create Date: 2020-05-31 23:53:35.848651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099a686e6130'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('reduction_factor', sa.Float(), nullable=True),
    sa.Column('savings', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('solution_text', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_category'), 'action', ['category'], unique=False)
    op.create_index(op.f('ix_action_description'), 'action', ['description'], unique=False)
    op.create_index(op.f('ix_action_name'), 'action', ['name'], unique=True)
    op.create_index(op.f('ix_action_reduction_factor'), 'action', ['reduction_factor'], unique=False)
    op.create_index(op.f('ix_action_reference'), 'action', ['reference'], unique=False)
    op.create_index(op.f('ix_action_savings'), 'action', ['savings'], unique=False)
    op.create_index(op.f('ix_action_sector'), 'action', ['sector'], unique=False)
    op.create_index(op.f('ix_action_solution_text'), 'action', ['solution_text'], unique=False)
    op.create_table('comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a1_id', sa.Integer(), nullable=True),
    sa.Column('a2_id', sa.Integer(), nullable=True),
    sa.Column('votes_1', sa.Integer(), nullable=True),
    sa.Column('votes_2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['a1_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['a2_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_a1_id'), 'comparison', ['a1_id'], unique=False)
    op.create_index(op.f('ix_comparison_a2_id'), 'comparison', ['a2_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparison_a2_id'), table_name='comparison')
    op.drop_index(op.f('ix_comparison_a1_id'), table_name='comparison')
    op.drop_table('comparison')
    op.drop_index(op.f('ix_action_solution_text'), table_name='action')
    op.drop_index(op.f('ix_action_sector'), table_name='action')
    op.drop_index(op.f('ix_action_savings'), table_name='action')
    op.drop_index(op.f('ix_action_reference'), table_name='action')
    op.drop_index(op.f('ix_action_reduction_factor'), table_name='action')
    op.drop_index(op.f('ix_action_name'), table_name='action')
    op.drop_index(op.f('ix_action_description'), table_name='action')
    op.drop_index(op.f('ix_action_category'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###
