"""empty message

Revision ID: 19a5f96ef69f
Revises: d760ef302128
Create Date: 2020-05-31 00:01:34.885593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a5f96ef69f'
down_revision = 'd760ef302128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action') as batch_op:
        batch_op.drop_column('reduction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('reduction', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
