"""empty message

Revision ID: 1dfb554cf18e
Revises: 86f65a33b37a
Create Date: 2020-07-17 14:44:07.589809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfb554cf18e'
down_revision = '86f65a33b37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emission', sa.Column('variation', sa.String(), nullable=True))
    op.create_index(op.f('ix_emission_variation'), 'emission', ['variation'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emission_variation'), table_name='emission')
    op.drop_column('emission', 'variation')
    # ### end Alembic commands ###
