"""empty message

Revision ID: 6281b6c04511
Revises: a16ce35689f4
Create Date: 2020-05-30 21:44:03.609718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6281b6c04511'
down_revision = 'a16ce35689f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('savings', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_category'), 'action', ['category'], unique=False)
    op.create_index(op.f('ix_action_description'), 'action', ['description'], unique=False)
    op.create_index(op.f('ix_action_name'), 'action', ['name'], unique=True)
    op.create_index(op.f('ix_action_savings'), 'action', ['savings'], unique=False)
    op.create_index(op.f('ix_action_sector'), 'action', ['sector'], unique=False)
    op.create_table('comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action1_id', sa.Integer(), nullable=True),
    sa.Column('action2_id', sa.Integer(), nullable=True),
    sa.Column('votes_1', sa.Integer(), nullable=True),
    sa.Column('votes_2', sa.Integer(), nullable=True),
    sa.Column('doesnshowup', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['action1_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['action2_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparison')
    op.drop_index(op.f('ix_action_sector'), table_name='action')
    op.drop_index(op.f('ix_action_savings'), table_name='action')
    op.drop_index(op.f('ix_action_name'), table_name='action')
    op.drop_index(op.f('ix_action_description'), table_name='action')
    op.drop_index(op.f('ix_action_category'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###
