"""empty message

Revision ID: 690ae32c02de
Revises: 6281b6c04511
Create Date: 2020-05-30 22:48:02.582723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690ae32c02de'
down_revision = '6281b6c04511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('solution_text', sa.String(), nullable=True))
    op.create_index(op.f('ix_action_solution_text'), 'action', ['solution_text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_solution_text'), table_name='action')
    op.drop_column('action', 'solution_text')
    # ### end Alembic commands ###
