"""empty message

Revision ID: a16ce35689f4
Revises: 6f438609c1c5
Create Date: 2020-05-30 21:06:24.589370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16ce35689f4'
down_revision = '6f438609c1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('testfield2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'testfield2')
    # ### end Alembic commands ###
