"""empty message

Revision ID: d760ef302128
Revises: 690ae32c02de
Create Date: 2020-05-30 23:01:55.133577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd760ef302128'
down_revision = '690ae32c02de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('reduction', sa.String(), nullable=True))
    op.create_index(op.f('ix_action_reduction'), 'action', ['reduction'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_reduction'), table_name='action')
    op.drop_column('action', 'reduction')
    # ### end Alembic commands ###
