"""empty message

Revision ID: e275f11384c2
Revises: 19a5f96ef69f
Create Date: 2020-05-31 00:24:12.800930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e275f11384c2'
down_revision = '19a5f96ef69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('action', sa.Column('reference', sa.String(), nullable=True))
    op.create_index(op.f('ix_action_reference'), 'action', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_reference'), table_name='action')
    op.drop_column('action', 'reference')
    op.drop_column('action', 'comment')
    # ### end Alembic commands ###
